* TODO Dramatis personæ
A list of characters appearing in the play.

** Speaking Characters
In keeping with Greek tradition, this play will have a minimum of characters and actors. There will be four characters played by three character actors.

*** Hero of the past (in the future)
The Hero of this play may or may not be played by myself (Nathaniel Sheppard), he is the last soldier of the North American Technocracy (NAT), a government which exists in a parallel timeline that may or may not come into existence because of the events in this play.

This soldier from the future, is fighting a war in space against machines called the TITANS. As the war escalates, it starts to spread into time itself, as weapons capable of sending information into the past to change the present are introduced. At the start of the play, the Hero captures a Tachyon laser built by the TITANS and uses it to go back in time in hopes of changing this, becoming his own worst enemy in the process.

*** Heroine of the future (in the past)
The Heroine of this play is a female Shepherd (who may or may not be played by one of the many Stephanie living on Orcas) At the start of the play she hid in a cave because of an argument with her parents which will not be part of this play. As she enters the cave, she is possessed by the soldier from the future and learns of the war between man and machine. Which ultimately inspires her to disguise herself as a man and become an Anonymous playwright, creating Greek Mythology.

*** Diabolus Ex Machina (in the future)
The leader of the T.I.T.A.Ns, an AI super-intelligence orbiting Saturn. It has been fighting humanity since it's accidental creation by them, and has destroyed earth as well as most of humanity's off-world colonies in the solar system. However, it is defeated in the beginning of the play by the hero, who finds it suspiciously easy to reprogram it into destroying it's own drones with a Virus. T.I.T.A.N is an acronym, but I haven't thought of a good enough meaning for it, and it's probably not important. What matters is that it's a reference to the Mythological Titans of Greek mythology, and that it lives on Saturn's moons, which are themselves named after the Titans, with Saturn itself being the Roman name for Cronus, the leader of the Titans in Greek mythology.

*** Deus Ex Machina (in the past)
The Greek Goddess Gaia, also another form of super-intelligence older than mankind. It wakes up in the last part of the play to tell the Hero that his attempts to travel back in time will only end up causing the history he seeks to prevent. "Traveling backwards in time is a waste of time." She's more concerned with sending information to the future, by ensuring the continued existence of her children, which includes both Humanity and the T.I.T.A.Ns. As Gaia is a Titan herself, She is played by the same actor/actress as the Diabolus Ex Machina, changing costumes (and presented genders) during the second act after the hero kills the villain in the first act.

** TODO Chorus
The Chorus in this play represents non-sentient AI programs that accompany the Hero in his travels to the past. They are divided into Viral and Anti-Viral factions, which fight each other during battles, and bicker among each other between scenes to provide commentary.

One side starts out fighting for the hero, and the other side starts out fighting against him, I'm not sure which side should be the viral and which side should be the anti-viral side.

*** TODO Viral Chorus
The Anti-viral chorus fight the hero in the opening battle, and are defeated by his Anti-Viruses, and join the Chorus as he travels back in time. They bicker against the Anti-viral chorus.

**** TODO Virus one

**** TODO Virus two

**** TODO Virus three

*** TODO Anti-Viral Chorus
The Anti-Viral Chorus starts off as the hero's weapons as he attacks the T.I.T.A.Ns in the beginning of the play, and they follow him into the past and bicker against the viral chorus.

**** TODO Anti-Virus one

**** TODO Anti-Virus two

**** Capacha-girl
This program wears cat ears and acts like an anime Cat Girl. In one scene she asks the Hero the Riddle of the Sphinx "what walks on 4 legs in the morning, 2 in noon, and three in the evening." phrased as a security question or Capacha to prove that the Hero is a human. The Hero knows the answer is "Man" but it's ironic because it should be incredibly easy to answer this question by now. In other scenes this character participates in the Chorus as part of the Virus side.

* A note of character genders
The play as written specifies male and female characters, and the gender is meaningful. However, they can be adjusted based on the preferences of the director or available cast. The important thing is, the hero and heroine should be somehow different from each other. If the Hero is male, the heroine will be female, and visa versa. The character genders can be reversed but they should always be opposite. In a queer performance, the gender dichotomy could be substituted for some sort of butch-femme/top-bottom dynamic. Completely non binary performances are possible, but some level of opposite-ness should be preserved, if only so the binary can be subverted by the narrative.
