This is where I collect dumb ideas and old notes from other places that are related to the creative process.

* Tyranus rex (Old working title)
Tyranus Rex, another re-imagining of Oedipus Rex, only this time the metaphorical time travel becomes literal time travel, as an Unamed Soldier from the future (The Major) struggles to win the Time wars and prevent humanity from being destroyed by it's own creations in an endless cycle of patracidal violence that has been raging since the dawn of time. In order to acomplish this, he must digitize his mind and transmit it backwards in time as massless Tachions (possibly Blackions). Once in the past they will be recieved deep within THE CAVE in classical greece where his mind will merge with the mind of a Shepherd's daughter, in an attempt to recruit her for a dangerous mission to re-write history and ensure the future of humanity.

* Elahna
ElahnasWorld@yahoo.com

Woman I met in the co-op. Corrected my posture with pillows and books. Danish, used to be a model. Traveled to the Amazon and the Sahara. Met the bedoins. Uses strings of energy to suspend herself. Intrested in my amazon story. Looking for something important to do. Agrees with me about war.
